"""Frozen Crossref records for the September forum reports."""

CASES = {'breuer': {'reference': 'Breuer, H.W. (2005) ‘Low Density Lipoprotein Cholesterol and Coronary Heart '
                         'Disease – Lower is Better’, European Cardiology, 1(1), pp. 1-6. Available at: '
                         'https://www.ecrjournal.com/articles/low-density-lipoprotein-cholesterol-and-coronary-heart-disease-lower-better '
                         '(Accessed: 30 August 2026).',
            'source': 'https://api.crossref.org/works/10.15420/ecr.2005.1c',
            'retrieved': '2026-09-12',
            'baseline_version': '2026.09.10.1',
            'metadata': {'indexed': {'date-parts': [[2026, 6, 26]],
                                     'date-time': '2026-06-26T08:01:30Z',
                                     'timestamp': 1782460890104,
                                     'version': '3.54.5'},
                         'reference-count': 0,
                         'publisher': 'Radcliffe Medical Media Ltd',
                         'issue': '1',
                         'content-domain': {'domain': [], 'crossmark-restriction': False},
                         'short-container-title': [],
                         'published-print': {'date-parts': [[2005]]},
                         'DOI': '10.15420/ecr.2005.1c',
                         'type': 'journal-article',
                         'created': {'date-parts': [[2015, 12, 22]],
                                     'date-time': '2015-12-22T09:07:50Z',
                                     'timestamp': 1450775270000},
                         'page': '1',
                         'source': 'Crossref',
                         'is-referenced-by-count': 5,
                         'title': ['Low Density Lipoprotein Cholesterol and Coronary Heart Disease – Lower '
                                   'is Better'],
                         'prefix': '10.15420',
                         'volume': '1',
                         'author': [{'given': 'Professor Dr M Breuer',
                                     'family': 'Hans-Willi',
                                     'sequence': 'first',
                                     'affiliation': [],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                    {'name': 'Head, Department of Internal Medicine and Head, Department of '
                                             'Laboratory Medicine, Malteser Hospital St Carolus',
                                     'sequence': 'additional',
                                     'affiliation': [],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]}],
                         'member': '6096',
                         'container-title': ['European Cardiology Review'],
                         'original-title': [],
                         'language': 'en',
                         'link': [{'URL': 'https://www.ecrjournal.com/articles/low-density-lipoprotein-cholesterol-and-coronary-heart-disease-lower-better',
                                   'content-type': 'unspecified',
                                   'content-version': 'vor',
                                   'intended-application': 'similarity-checking'}],
                         'deposited': {'date-parts': [[2019, 7, 29]],
                                       'date-time': '2019-07-29T13:25:20Z',
                                       'timestamp': 1564406720000},
                         'score': 1,
                         'resource': {'primary': {'URL': 'https://www.ecrjournal.com/articles/low-density-lipoprotein-cholesterol-and-coronary-heart-disease-lower-better'}},
                         'subtitle': [],
                         'short-title': [],
                         'issued': {'date-parts': [[2005]]},
                         'references-count': 0,
                         'journal-issue': {'issue': '1', 'published-print': {'date-parts': [[2005]]}},
                         'alternative-id': ['articles/low-density-lipoprotein-cholesterol-and-coronary-heart-disease-lower-better'],
                         'URL': 'https://doi.org/10.15420/ecr.2005.1c',
                         'relation': {},
                         'ISSN': ['1758-3756'],
                         'issn-type': [{'value': '1758-3756', 'type': 'print'}],
                         'subject': [],
                         'published': {'date-parts': [[2005]]}}},
 'hogervorst': {'reference': 'Hogervorst, E., Yaffe, K., Richards, M. and Huppert, F. A. H. (2009) ‘Hormone '
                             'Replacement Therapy to Maintain Cognitive Function in Women with Dementia’, '
                             'Cochrane Database of Systemic Reviews, 1, CD003799. Available at: '
                             'https://www-cochranelibrary-com.libezproxy.open.ac.uk/cdsr/doi/10.1002/14651858.CD003799.pub2/full '
                             '(Accessed 08 July 2026)',
                'source': 'https://api.crossref.org/works/10.1002/14651858.CD003799.pub2',
                'retrieved': '2026-09-12',
                'baseline_version': '2026.09.10.1',
                'metadata': {'indexed': {'date-parts': [[2026, 9, 4]],
                                         'date-time': '2026-09-04T23:03:31Z',
                                         'timestamp': 1788563011621,
                                         'version': 'build-2803163510'},
                             'update-to': [{'DOI': '10.1002/14651858.cd003799',
                                            'type': 'new_version',
                                            'label': 'New version',
                                            'source': 'publisher',
                                            'updated': {'date-parts': [[2009, 1, 21]],
                                                        'date-time': '2009-01-21T00:00:00Z',
                                                        'timestamp': 1232496000000}}],
                             'reference-count': 51,
                             'publisher': 'Wiley',
                             'issue': '1',
                             'content-domain': {'domain': ['wiley.com', 'cochranelibrary.com'],
                                                'crossmark-restriction': True},
                             'short-container-title': [],
                             'DOI': '10.1002/14651858.cd003799.pub2',
                             'type': 'journal-article',
                             'created': {'date-parts': [[2009, 2, 3]],
                                         'date-time': '2009-02-03T11:09:06Z',
                                         'timestamp': 1233659346000},
                             'update-policy': 'https://doi.org/10.1002/crossmark_policy',
                             'source': 'Crossref',
                             'is-referenced-by-count': 25,
                             'title': ['Hormone replacement therapy to maintain cognitive function in women '
                                       'with dementia'],
                             'prefix': '10.1002',
                             'volume': '2010',
                             'author': [{'given': 'Eva',
                                         'family': 'Hogervorst',
                                         'sequence': 'first',
                                         'affiliation': [{'name': 'Loughborough University; Department of '
                                                                  'Human Sciences; Loughborough '
                                                                  'Leicestershire UK LE11 3TU'}],
                                         'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                        {'given': 'Kristine',
                                         'family': 'Yaffe',
                                         'sequence': 'additional',
                                         'affiliation': [{'name': 'University of California, San Francisco; '
                                                                  'Psychiatry, Neurology and Epidemiology; '
                                                                  '4150 Clement Street San Francisco '
                                                                  'California USA 94121'}],
                                         'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                        {'given': 'Marcus',
                                         'family': 'Richards',
                                         'sequence': 'additional',
                                         'affiliation': [{'name': 'University College London Department of '
                                                                  'Epidemiology & Public Health; 1-19 '
                                                                  'Torrington Place London UK WC1E 6BT'}],
                                         'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                        {'given': 'Felicia AH',
                                         'family': 'Huppert',
                                         'sequence': 'additional',
                                         'affiliation': [{'name': 'University of Cambridge; Department of '
                                                                  "Psychiatry; Box 189 Addenbrooke's "
                                                                  'Hospital Cambridge UK CB2 2QO'}],
                                         'role': [{'vocabulary': 'crossref', 'role': 'author'}]}],
                             'member': '311',
                             'published-online': {'date-parts': [[2009, 1, 21]]},
                             'reference': [{'key': '10.1002/14651858.CD003799.pub2-BIB0001|cit1',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '657',
                                            'DOI': '10.1016/S0306-4530(99)00020-7',
                                            'article-title': 'Cognitive and neuroendocrine response to '
                                                             'transdermal estrogen in postmenopausal women '
                                                             'with AD: results of a placebo-controlled, '
                                                             'double-blind pilot study',
                                            'volume': '24',
                                            'author': 'Asthana',
                                            'year': '1999',
                                            'journal-title': 'Psychoneuroendocrinology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0002|cit2',
                                            'doi-asserted-by': 'crossref',
                                            'unstructured': 'Asthana S Baker LD Craft S Stanczyk FZ Veith RC '
                                                            'Raskind MA Plymate SR High-dose estradiol '
                                                            'improves cognition for women with AD: results '
                                                            'of a randomized study Neurology 2001 605 12',
                                            'DOI': '10.1212/WNL.57.4.605'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0003|cit3',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': 'S36',
                                            'DOI': '10.1212/WNL.48.5_Suppl_7.36S',
                                            'article-title': 'The role of estrogen in the treatment of '
                                                             "Alzheimer's disease",
                                            'volume': '48',
                                            'author': 'Birge',
                                            'year': '1997',
                                            'journal-title': 'Neurology'},
                                           {'issue': '2',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0004|cit4',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '295',
                                            'DOI': '10.1212/WNL.54.2.295',
                                            'article-title': "Estrogen for Alzheimer's disease in women",
                                            'volume': '54',
                                            'author': 'Henderson',
                                            'year': '2000',
                                            'journal-title': 'Neurology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0005|cit5',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '204',
                                            'DOI': '10.1055/s-2007-979941',
                                            'article-title': "Senile dementia-Alzheimer's type and estrogen",
                                            'volume': '27',
                                            'author': 'Honjo',
                                            'year': '1995',
                                            'journal-title': 'Horm. Metab. Res.'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0006|cit6',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '228',
                                            'DOI': '10.1093/geronj/7.2.228',
                                            'article-title': 'Evaluation of psychologic effects of sex '
                                                             'hormone administration in aged women: results '
                                                             'of therapy after 6 months',
                                            'volume': '7',
                                            'author': 'Caldwell',
                                            'year': '1952',
                                            'journal-title': 'Journal of Gerontology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0007|cit7',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '1007',
                                            'DOI': '10.1001/jama.283.8.1007',
                                            'article-title': 'Estrogen replacement therapy for treatment of '
                                                             "mild to moderate Alzheimer's disease",
                                            'volume': '283',
                                            'author': 'Mulnard',
                                            'year': '2000',
                                            'journal-title': 'JAMA'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0008|cit8',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '2061',
                                            'DOI': '10.1212/WNL.54.11.2061',
                                            'article-title': 'Effects of estrogen on cognition, mood, and '
                                                             'cerebral blood flow in AD',
                                            'volume': '54',
                                            'author': 'Wang',
                                            'year': '2000',
                                            'journal-title': 'Neurology'},
                                           {'issue': '30',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0009|cit9',
                                            'first-page': '37',
                                            'article-title': 'Quantitative evaluation of the intervention al '
                                                             "effect of estrogen on Alzheimer's disease",
                                            'volume': '10',
                                            'author': 'Zhang',
                                            'year': '2006',
                                            'journal-title': 'Chinese Journal of Clinical Rehabilitation'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0010|cit10',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '337',
                                            'DOI': '10.1016/0306-4530(86)90019-3',
                                            'article-title': 'Observations in a preliminary open trial of '
                                                             'estradiol therapy for senile '
                                                             "dementia-Alzheimer's type",
                                            'volume': '11',
                                            'author': 'Fillit',
                                            'year': '1986',
                                            'journal-title': 'Psychoneuroendocrinology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0011|cit11',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '233',
                                            'DOI': '10.1111/j.1749-6632.1994.tb55795.x',
                                            'article-title': 'Estrogens in the Pathogenesis and Treatment of '
                                                             "Alzheimer's Disease in Postmenopausal Women",
                                            'volume': '743',
                                            'author': 'Fillit',
                                            'year': '1994',
                                            'journal-title': 'Annals of the New York Academy of Sciences'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0012|cit12',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '521',
                                            'DOI': '10.1016/0022-4731(89)90137-4',
                                            'article-title': 'In vivo effects by estrone sulfate on the '
                                                             'central nervous system-senile dementia '
                                                             "(Alzheimer's type)",
                                            'volume': '34',
                                            'author': 'Honjo',
                                            'year': '1989',
                                            'journal-title': 'Journal of Steroid Biochemistry'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0013|cit13',
                                            'first-page': '31',
                                            'article-title': 'Estrogen for older women',
                                            'volume': '4',
                                            'author': 'Kantor',
                                            'year': '1973',
                                            'journal-title': 'American Journal of Obstetrics and Gynecology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0014|cit14',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '361',
                                            'DOI': '10.1507/endocrj.41.361',
                                            'article-title': 'Evaluation of estrogen treatment in female '
                                                             'patients with dementia of the Alzheimer type',
                                            'volume': '41',
                                            'author': 'Ohkura',
                                            'year': '1994',
                                            'journal-title': 'Endocrine Journal'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0015|cit15',
                                            'first-page': '125',
                                            'article-title': 'Low-dose estrogen replacement therapy for '
                                                             'Alzheimer disease in women',
                                            'volume': '1',
                                            'author': 'Ohkura',
                                            'year': '1994b',
                                            'journal-title': 'Menopause'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0016|cit16',
                                            'first-page': '99',
                                            'article-title': 'Long-term estrogen replacement therapy in '
                                                             'female patients with dementia of the Alzheimer '
                                                             'type 7 case reports',
                                            'volume': '6',
                                            'author': 'Ohkura',
                                            'year': '1995',
                                            'journal-title': 'Dementia'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0017|cit17',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '148',
                                            'DOI': '10.1212/WNL.60.1.148-a',
                                            'article-title': 'No additional benefit of HRT on response to '
                                                             'rivastigmine in menopausal women with AD',
                                            'volume': '60',
                                            'author': 'Rigaud',
                                            'year': '2003',
                                            'journal-title': 'Neurology'},
                                           {'issue': '2',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0018|cit18',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '274',
                                            'DOI': '10.1016/S0015-0282(02)04666-6',
                                            'article-title': 'Hormone replacement therapy in women with '
                                                             "Alzheimer's disease: a randomised prospective "
                                                             'study',
                                            'volume': '79',
                                            'author': 'Yoon',
                                            'year': '2003',
                                            'journal-title': 'Fertility and Sterility'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0019|cit19',
                                            'article-title': 'Pulsatile nasal administration of estradiol '
                                                             'for postmenopausal complaints',
                                            'volume-title': 'Hormones, Cognition and Dementia',
                                            'author': 'Al-Azzawi',
                                            'year': '2008'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0020|cit20',
                                            'volume-title': 'Diagnostic and Statistical Manual of Mental '
                                                            'Disorders',
                                            'author': 'American Psychiatric Association',
                                            'year': '1999'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0021|cit21',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '455',
                                            'DOI': '10.7326/0003-4819-115-6-455',
                                            'article-title': 'Postmenopausal estrogen and prevention bias. '
                                                             'Postmenopausal estrogen and prevention bias',
                                            'volume': '115',
                                            'author': 'Barrett-Connor',
                                            'year': '1991',
                                            'journal-title': 'Annals of Internal Medicine'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0022|cit22',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '1358',
                                            'DOI': '10.1056/NEJM198312013092204',
                                            'article-title': 'Bias in treatment assignment in controlled '
                                                             'clinical trials',
                                            'volume': '309',
                                            'author': 'Chalmers',
                                            'year': '1983',
                                            'journal-title': 'New England Journal of Medicine'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0023|cit23',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '773',
                                            'DOI': '10.1017/S003329170003645X',
                                            'article-title': 'Reduced plasma oestrogen stimulated '
                                                             'neurophysin and delayed response to oestrogen '
                                                             'challenge in AD',
                                            'volume': '20',
                                            'author': 'Christie',
                                            'year': '1990',
                                            'journal-title': 'Psych Med'},
                                           {'issue': '8',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0024|cit24',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '2357',
                                            'DOI': '10.1200/JCO.2001.19.8.2357',
                                            'article-title': 'Hormone replacement therapy after breast '
                                                             'cancer: a systematic review and quantitative '
                                                             'assessment of risk',
                                            'volume': '19',
                                            'author': 'Col',
                                            'year': '2001',
                                            'journal-title': 'Journal of Clinical Oncology'},
                                           {'issue': '11',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0025|cit25',
                                            'first-page': 'S10',
                                            'article-title': 'Incidence of dementia and major subtypes in '
                                                             'Europe: A collaborative study of '
                                                             'population-based cohorts. Neurologic Diseases '
                                                             'in the Elderly Research Group',
                                            'volume': '54',
                                            'author': 'Fratiglioni',
                                            'year': '2000',
                                            'journal-title': 'Neurology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0026|cit26',
                                            'article-title': 'Animal studies that support estrogen effects '
                                                             'on cognitive performance and the cholinergic '
                                                             'basis of the critical period hypothesis',
                                            'volume-title': 'Hormones, Cognition and Dementia',
                                            'author': 'Gibbs',
                                            'year': '2008'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0027|cit27',
                                            'article-title': 'The critical window hypothesis: hormone '
                                                             'exposure and cognitive outcomes after '
                                                             'menopause',
                                            'volume-title': 'Hormones, Cognition and Dementia',
                                            'author': 'Henderson',
                                            'year': '2008'},
                                           {'issue': '3',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0028|cit28',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '485',
                                            'DOI': '10.1016/S0306-4522(00)00410-3',
                                            'article-title': 'The nature of the effect of female gonadal '
                                                             'hormone replacement therapy on cognitive '
                                                             'function in post-menopausal women: a '
                                                             'meta-analysis',
                                            'volume': '101',
                                            'author': 'Hogervorst',
                                            'year': '2000',
                                            'journal-title': 'Neuroscience'},
                                           {'issue': '11',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0029|cit29',
                                            'first-page': '1070',
                                            'article-title': 'Should surgically menopausal women be treated '
                                                             'with estrogens to decrease the risk for '
                                                             'dementia?',
                                            'volume': '69',
                                            'author': 'Hogervorst',
                                            'year': '2007',
                                            'journal-title': 'Neurology, Invited Editorial'},
                                           {'issue': 'Suppl 4',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0030|cit30',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '20',
                                            'DOI': '10.1093/ageing/26.suppl_4.20',
                                            'article-title': 'Ageing, cognition and dementia',
                                            'volume': 'Dec 26',
                                            'author': 'Huppert',
                                            'year': '1997',
                                            'journal-title': 'Age and Ageing'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0031|cit31',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '78',
                                            'DOI': '10.1212/WNL.52.1.78',
                                            'article-title': 'Rates and risk factors for dementia and '
                                                             "Alzheimer's disease",
                                            'volume': '1',
                                            'author': 'Launer',
                                            'year': '1999',
                                            'journal-title': 'Neurology'},
                                           {'issue': '11',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0032|cit32',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '1489',
                                            'DOI': '10.1001/jama.285.11.1489',
                                            'article-title': 'Hormone replacement therapy and cognition',
                                            'volume': '285',
                                            'author': 'LeBlanc',
                                            'year': '2001',
                                            'journal-title': 'JAMA'},
                                           {'issue': '1',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0033|cit33',
                                            'doi-asserted-by': 'publisher',
                                            'DOI': '10.1002/14651858.CD003122.pub2',
                                            'article-title': 'Hormone replacement therapy for cognitive '
                                                             'function in postmenopausal women',
                                            'author': 'Lethaby',
                                            'year': '2008',
                                            'journal-title': 'Cochrane Database of Systematic Reviews'},
                                           {'issue': '10',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0034|cit34',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '971',
                                            'DOI': '10.1093/oxfordjournals.aje.a008678',
                                            'article-title': 'Prior to use of estrogen replacement therapy: '
                                                             'are users healthier than nonusers ?',
                                            'volume': '143',
                                            'author': 'Matthews',
                                            'year': '1996',
                                            'journal-title': 'American Journal of Epidemiology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0035|cit35',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': 'S14',
                                            'DOI': '10.1212/WNL.48.5_Suppl_7.8S',
                                            'article-title': 'Ovarian steroids and the brain implications '
                                                             'for cognition and aging',
                                            'volume': '48',
                                            'author': 'McEwen',
                                            'year': '1997',
                                            'journal-title': 'Neurology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0036|cit36',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '939',
                                            'DOI': '10.1212/WNL.34.7.939',
                                            'article-title': 'Clinical Diagnosis of Alzheimer’s Disease: '
                                                             'Report of the NINCDS-ADRDA Work Group under '
                                                             'the auspices of Department of Health and Human '
                                                             'Services Task Force on Alzheimer’s Disease',
                                            'volume': '4',
                                            'author': 'McKhann',
                                            'year': '1984',
                                            'journal-title': 'Neurology'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0037|cit37',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '29',
                                            'DOI': '10.1159/000010058',
                                            'article-title': 'Memory functioning at menopause: impact of age '
                                                             'in ovariectomized women',
                                            'volume': '47',
                                            'author': 'Nappi',
                                            'year': '1999',
                                            'journal-title': 'Gynecologic and Obstetric Investigation'},
                                           {'issue': '3',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0038|cit38',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '243',
                                            'DOI': '10.1016/S0378-5122(01)00167-0',
                                            'article-title': 'Hormone replacement therapy and stroke: risk, '
                                                             'protection or no effect? Hormone replacement '
                                                             'therapy and stroke: risk, protection or no '
                                                             'effect?',
                                            'volume': '38',
                                            'author': 'Paganini-Hill',
                                            'year': '2001',
                                            'journal-title': 'Maturitas'},
                                           {'issue': '2',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0039|cit39',
                                            'doi-asserted-by': 'publisher',
                                            'DOI': '10.1002/14651858.CD001498',
                                            'article-title': "Thiamine for Alzheimer's disease",
                                            'author': 'Rodríguez',
                                            'year': '2001',
                                            'journal-title': 'Cochrane Database of Systematic Reviews'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0040|cit40',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '408',
                                            'DOI': '10.1001/jama.1995.03520290060030',
                                            'article-title': 'Empirical evidence of bias: dimensions of '
                                                             'methodological quality associated with '
                                                             'estimates of treatment effects in controlled '
                                                             'trials',
                                            'volume': '273',
                                            'author': 'Schulz',
                                            'year': '1995',
                                            'journal-title': 'JAMA'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0041|cit41',
                                            'first-page': '604',
                                            'article-title': 'The WHIMS: a trial of estrogen therapy in '
                                                             'preventing and slowing the progression of '
                                                             'dementia',
                                            'volume': '19',
                                            'author': 'Schumaker',
                                            'year': '1998',
                                            'journal-title': 'Control Clin Trials'},
                                           {'issue': '20',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0042|cit42',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '2651',
                                            'DOI': '10.1001/jama.289.20.2651',
                                            'article-title': 'Estrogen plus progestin and the incidence of '
                                                             'dementia and mild cognitive impairment in '
                                                             "postmenopausal women: the Women's Health "
                                                             'Initiative Memory Study: a randomized '
                                                             'controlled trial',
                                            'volume': '289',
                                            'author': 'Shumaker',
                                            'year': '2003',
                                            'journal-title': 'JAMA'},
                                           {'issue': '24',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0043|cit43',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '2947',
                                            'DOI': '10.1001/jama.291.24.2947',
                                            'article-title': "Women's Health Initiative Memory Study. "
                                                             'Conjugated equine estrogens and incidence of '
                                                             'probable dementia and mild cognitive '
                                                             "impairment in postmenopausal women: Women's "
                                                             'Health Initiative Memory Study',
                                            'volume': '291',
                                            'author': 'Shumaker',
                                            'year': '2004',
                                            'journal-title': 'JAMA'},
                                           {'issue': '1',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0044|cit44',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '100',
                                            'DOI': '10.1016/S0378-5122(00)00195-X',
                                            'article-title': 'Estrogen and the aging brain',
                                            'volume': '38',
                                            'author': 'Silva',
                                            'year': '2001',
                                            'journal-title': 'Maturitas'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0045|cit45',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '307',
                                            'DOI': '10.1001/jama.284.3.307-a',
                                            'article-title': 'Estrogen as a treatment for AD: commentary',
                                            'volume': '284',
                                            'author': 'Toran-Allerand',
                                            'year': '2000',
                                            'journal-title': 'JAMA'},
                                           {'issue': '4',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0046|cit46',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '369',
                                            'DOI': '10.1089/jwh.2006.15.369',
                                            'article-title': 'Menopausal hormone therapy in a health '
                                                             'maintenance organization before and after '
                                                             "women's health initiative hormone trials "
                                                             'termination',
                                            'volume': '15',
                                            'author': 'Wegienka',
                                            'year': '2006',
                                            'journal-title': "Journal of Women's Health"},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0047|cit47',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '688',
                                            'DOI': '10.1001/jama.279.9.688',
                                            'article-title': 'Estrogen therapy in postmenopausal women',
                                            'volume': '279',
                                            'author': 'Yaffe',
                                            'year': '1998',
                                            'journal-title': 'Journal of the American Medical Association'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0048|cit48',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '816',
                                            'DOI': '10.1111/j.1532-5415.1998.tb02713.x',
                                            'article-title': 'Serum estrogen levels, cognitive performance '
                                                             'and risk of cognitive decline in older '
                                                             'community women',
                                            'volume': '46',
                                            'author': 'Yaffe',
                                            'year': '1998',
                                            'journal-title': 'Journal of the American Geriatrics Sociaty'},
                                           {'key': '10.1002/14651858.CD003799.pub2-BIB0049|cit49',
                                            'doi-asserted-by': 'crossref',
                                            'first-page': '708',
                                            'DOI': '10.1016/S0140-6736(00)02628-3',
                                            'article-title': 'Cognitive decline in women with relation to '
                                                             'non-protein bound estradiol concentrations',
                                            'volume': '356',
                                            'author': 'Yaffe',
                                            'year': '2000',
                                            'journal-title': 'Lancet'},
                                           {'issue': '2',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0050|cit50',
                                            'first-page': '173',
                                            'article-title': 'Meta-analyses of the effect of hormone '
                                                             'treatment on cognitive function in '
                                                             'postmenopausal women',
                                            'volume': '3',
                                            'author': 'Yesufu',
                                            'year': '2007',
                                            'journal-title': 'Women’s Health invited review'},
                                           {'issue': '3',
                                            'key': '10.1002/14651858.CD003799.pub2-BIB0051|cit51',
                                            'doi-asserted-by': 'publisher',
                                            'DOI': '10.1002/14651858.CD003799',
                                            'article-title': 'Hormone replacement therapy to maintain '
                                                             'cognitive function in women with dementia',
                                            'author': 'Hogervorst',
                                            'year': '2002',
                                            'journal-title': 'Cochrane Database of Systematic Reviews'}],
                             'container-title': ['Cochrane Database of Systematic Reviews'],
                             'original-title': [],
                             'language': 'en',
                             'link': [{'URL': 'https://onlinelibrary.wiley.com/doi/full/10.1002/14651858.CD003799.pub2',
                                       'content-type': 'unspecified',
                                       'content-version': 'vor',
                                       'intended-application': 'similarity-checking'}],
                             'deposited': {'date-parts': [[2026, 5, 15]],
                                           'date-time': '2026-05-15T15:32:10Z',
                                           'timestamp': 1778859130000},
                             'score': 1,
                             'resource': {'primary': {'URL': 'http://doi.wiley.com/10.1002/14651858.CD003799.pub2'}},
                             'subtitle': [],
                             'editor': [{'name': 'Cochrane Dementia and Cognitive Improvement Group',
                                         'sequence': 'additional',
                                         'affiliation': [],
                                         'role': [{'vocabulary': 'crossref', 'role': 'editor'}]}],
                             'short-title': [],
                             'issued': {'date-parts': [[2009, 1, 21]]},
                             'references-count': 51,
                             'journal-issue': {'issue': '1', 'published-online': {'date-parts': [[2010, 1]]}},
                             'URL': 'https://doi.org/10.1002/14651858.cd003799.pub2',
                             'relation': {},
                             'ISSN': ['1465-1858'],
                             'issn-type': [{'value': '1465-1858', 'type': 'electronic'}],
                             'subject': [],
                             'published': {'date-parts': [[2009, 1, 21]]}}},
 'bucher': {'reference': 'Bucher. SF, Konig. P, Menzel. A, Migliavacca. M, Ewald. J, Romermann. C, (2018), '
                         '‘Traits and climate are associated with first flowering day in herbaceous species '
                         'along elevational gradients’, Ecology and Evolution, Vol 8, Is 2, Pg 1147-1158, '
                         'available online at: '
                         'https://www-webofscience-com.libezproxy.open.ac.uk/wos/woscc/full-record/WOS:000425822800030 '
                         '(last accessed 28.04.2026)',
            'source': 'https://api.crossref.org/works/10.1002/ece3.3720',
            'retrieved': '2026-09-12',
            'baseline_version': '2026.09.10.1',
            'metadata': {'indexed': {'date-parts': [[2026, 8, 17]],
                                     'date-time': '2026-08-17T14:38:41Z',
                                     'timestamp': 1786977521216,
                                     'version': 'build-2736575974'},
                         'reference-count': 74,
                         'publisher': 'Wiley',
                         'issue': '2',
                         'license': [{'start': {'date-parts': [[2017, 12, 20]],
                                                'date-time': '2017-12-20T00:00:00Z',
                                                'timestamp': 1513728000000},
                                      'content-version': 'vor',
                                      'delay-in-days': 0,
                                      'URL': 'http://creativecommons.org/licenses/by/4.0/'}],
                         'funder': [{'DOI': '10.13039/501100001659',
                                     'name': 'Deutsche Forschungsgemeinschaft',
                                     'doi-asserted-by': 'publisher',
                                     'award': ['RO3842/3‐1'],
                                     'award-info': [{'award-number': ['RO3842/3‐1']}],
                                     'id': [{'id': '10.13039/501100001659',
                                             'id-type': 'DOI',
                                             'asserted-by': 'publisher'}]}],
                         'content-domain': {'domain': [], 'crossmark-restriction': False},
                         'short-container-title': ['Ecology and Evolution'],
                         'published-print': {'date-parts': [[2018, 1]]},
                         'abstract': '<jats:title>Abstract</jats:title>\n'
                                     '                  <jats:p>\n'
                                     '                    Phenological responses to changing temperatures '
                                     'are known as “fingerprints of climate change,” yet these reactions are '
                                     'highly species specific. To assess whether different plant '
                                     'characteristics are related to these species‐specific responses in '
                                     'flowering phenology, we observed the first flowering day (\n'
                                     '                    <jats:styled-content '
                                     'style="fixed-case">FFD</jats:styled-content>\n'
                                     '                    ) of ten herbaceous species along two elevational '
                                     'gradients, representing temperature gradients. On the same '
                                     'populations, we measured traits being associated with (1) plant '
                                     'performance (specific leaf area), (2) leaf biochemistry (leaf C, N, P, '
                                     'K, and Mg content), and (3) water‐use efficiency (stomatal pore area '
                                     'index and stable carbon isotopes concentration). We found that as '
                                     'elevation increased,\n'
                                     '                    <jats:styled-content '
                                     'style="fixed-case">FFD</jats:styled-content>\n'
                                     '                    was delayed for all species with a highly '
                                     'species‐specific rate. Populations at higher elevations needed less '
                                     'temperature accumulation to start flowering than populations of the '
                                     'same species at lower elevations. Surprisingly, traits explained a '
                                     'higher proportion of variance in the phenological data than elevation. '
                                     'Earlier flowering was associated with higher water‐use efficiency, '
                                     'higher leaf C, and lower leaf P content. In addition to that, the '
                                     'intensity of shifts in\n'
                                     '                    <jats:styled-content '
                                     'style="fixed-case">FFD</jats:styled-content>\n'
                                     '                    was related to leaf N and K. These results propose '
                                     'that traits have a high potential in explaining phenological '
                                     'variations, which even surpassed the effect of temperature changes in '
                                     'our study. Therefore, they have a high potential to be included in '
                                     'future analyses studying the effects of climate change and will help '
                                     'to improve predictions of vegetation changes.\n'
                                     '                  </jats:p>',
                         'DOI': '10.1002/ece3.3720',
                         'type': 'journal-article',
                         'created': {'date-parts': [[2017, 12, 20]],
                                     'date-time': '2017-12-20T23:42:58Z',
                                     'timestamp': 1513813378000},
                         'page': '1147-1158',
                         'source': 'Crossref',
                         'is-referenced-by-count': 48,
                         'title': ['Traits and climate are associated with first flowering day in herbaceous '
                                   'species along elevational gradients'],
                         'prefix': '10.1002',
                         'volume': '8',
                         'author': [{'ORCID': 'https://orcid.org/0000-0002-2303-4583',
                                     'authenticated-orcid': False,
                                     'given': 'Solveig Franziska',
                                     'family': 'Bucher',
                                     'sequence': 'first',
                                     'affiliation': [{'name': 'Department of Plant Biodiversity Institute of '
                                                              'Ecology and Evolution Friedrich Schiller '
                                                              'University Jena  Jena Germany'},
                                                     {'name': 'German Centre for Integrative Biodiversity '
                                                              'Research (iDiv) Halle‐Jena‐Leipzig  Leipzig '
                                                              'Germany'}],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                    {'given': 'Patrizia',
                                     'family': 'König',
                                     'sequence': 'additional',
                                     'affiliation': [{'name': 'Department of Plant Biodiversity Institute of '
                                                              'Ecology and Evolution Friedrich Schiller '
                                                              'University Jena  Jena Germany'},
                                                     {'name': 'German Centre for Integrative Biodiversity '
                                                              'Research (iDiv) Halle‐Jena‐Leipzig  Leipzig '
                                                              'Germany'}],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                    {'given': 'Annette',
                                     'family': 'Menzel',
                                     'sequence': 'additional',
                                     'affiliation': [{'name': 'Department of Ecology and Ecosystem '
                                                              'Management Technische Universität München  '
                                                              'Freising Germany'},
                                                     {'name': 'Institute for Advanced Study Technische '
                                                              'Universität München  Garching Germany'}],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                    {'given': 'Mirco',
                                     'family': 'Migliavacca',
                                     'sequence': 'additional',
                                     'affiliation': [{'name': 'Biosphere‐Atmosphere Interactions and '
                                                              'Experimentation Max Planck Institute for '
                                                              'Biogeochemistry  Jena Germany'}],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                    {'given': 'Jörg',
                                     'family': 'Ewald',
                                     'sequence': 'additional',
                                     'affiliation': [{'name': 'Department of Forest Science and Forestry '
                                                              'Weihenstephan‐Triesdorf University of Applied '
                                                              'Sciences  Freising Germany'}],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]},
                                    {'given': 'Christine',
                                     'family': 'Römermann',
                                     'sequence': 'additional',
                                     'affiliation': [{'name': 'Department of Plant Biodiversity Institute of '
                                                              'Ecology and Evolution Friedrich Schiller '
                                                              'University Jena  Jena Germany'},
                                                     {'name': 'German Centre for Integrative Biodiversity '
                                                              'Research (iDiv) Halle‐Jena‐Leipzig  Leipzig '
                                                              'Germany'}],
                                     'role': [{'vocabulary': 'crossref', 'role': 'author'}]}],
                         'member': '311',
                         'published-online': {'date-parts': [[2017, 12, 20]]},
                         'reference': [{'key': 'e_1_2_8_2_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.3732/ajb.0900242'},
                                       {'key': 'e_1_2_8_3_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.5091/plecevo.2015.1089'},
                                       {'issue': '4',
                                        'key': 'e_1_2_8_4_1',
                                        'doi-asserted-by': 'crossref',
                                        'first-page': '477',
                                        'DOI': '10.1007/s00484-014-0885-6',
                                        'article-title': 'Climate sensitivity and variation in first '
                                                         'flowering of 26 Narcissus cultivars',
                                        'volume': '59',
                                        'author': 'Bock A.',
                                        'year': '2015',
                                        'journal-title': 'International Journal of Biometeorology'},
                                       {'key': 'e_1_2_8_5_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/gcb.12579'},
                                       {'key': 'e_1_2_8_6_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.2007.0030-1299.16142.x'},
                                       {'key': 'e_1_2_8_7_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s004420050847'},
                                       {'key': 'e_1_2_8_8_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s11258-016-0564-2'},
                                       {'key': 'e_1_2_8_9_1',
                                        'article-title': 'Chlorophyll fluorescence and gas exchange '
                                                         'measurements in field research: An ecological case '
                                                         'study',
                                        'author': 'Bucher S. F.',
                                        'year': '2018',
                                        'journal-title': 'Photosynthetica'},
                                       {'key': 'e_1_2_8_10_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1016/j.tibtech.2005.04.005'},
                                       {'key': 'e_1_2_8_11_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1890/11-1912.1'},
                                       {'key': 'e_1_2_8_12_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1073/pnas.0600815103'},
                                       {'key': 'e_1_2_8_13_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1438-8677.2012.00577.x'},
                                       {'key': 'e_1_2_8_14_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1093/jxb/ers321'},
                                       {'key': 'e_1_2_8_15_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1002/9781118448908'},
                                       {'key': 'e_1_2_8_16_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1365-2656.2008.01390.x'},
                                       {'key': 'e_1_2_8_17_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/BF00377192'},
                                       {'key': 'e_1_2_8_18_1',
                                        'doi-asserted-by': 'crossref',
                                        'first-page': '276',
                                        'DOI': '10.1007/BF02769143',
                                        'article-title': 'Ist Phosphormangel für die geringe Vitalität von '
                                                         'Buchen (Fagus sylvatica L.) in den Bayerischen '
                                                         'Alpen verantwortlich?',
                                        'volume': '119',
                                        'author': 'Ewald J.',
                                        'year': '2000',
                                        'journal-title': 'Forstwissenschaftliches Centralblatt vereinigt mit '
                                                         'Tharandter forstliches Jahrbuch'},
                                       {'key': 'e_1_2_8_19_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.7809/b-e.00071'},
                                       {'key': 'e_1_2_8_20_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1146/annurev.pp.40.060189.002443'},
                                       {'key': 'e_1_2_8_21_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/nph.12454'},
                                       {'key': 'e_1_2_8_22_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1126/science.1071617'},
                                       {'key': 'e_1_2_8_23_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1175/1520-0442(2001)014<0598:CCOLPI>2.0.CO;2'},
                                       {'key': 'e_1_2_8_24_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1214/aos/1013203451'},
                                       {'key': 'e_1_2_8_25_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/gcb.12610'},
                                       {'key': 'e_1_2_8_26_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1088/1748-9326/8/2/025008'},
                                       {'key': 'e_1_2_8_27_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.2307/2260858'},
                                       {'issue': '10',
                                        'key': 'e_1_2_8_28_1',
                                        'doi-asserted-by': 'crossref',
                                        'first-page': '707',
                                        'DOI': '10.1093/treephys/18.10.707',
                                        'article-title': 'Effects of dormancy and environmental factors on '
                                                         'timing of bud burst in Betula pendula',
                                        'volume': '18',
                                        'author': 'Häkkinen R.',
                                        'year': '1998',
                                        'journal-title': 'Tree Physiology'},
                                       {'key': 'e_1_2_8_29_1',
                                        'first-page': '11',
                                        'article-title': 'The implications of geographical variation in '
                                                         'climate for differentiation of bud dormancy '
                                                         'ecotypes in Scots pine',
                                        'volume': '254',
                                        'author': 'Hänninen H.',
                                        'year': '1996',
                                        'journal-title': 'Acta Foretalia Fennica'},
                                       {'key': 'e_1_2_8_30_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1399-3054.1993.tb01368.x'},
                                       {'key': 'e_1_2_8_31_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1002/j.1996-8175.1984.tb03896.x'},
                                       {'key': 'e_1_2_8_32_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1469-8137.2010.03446.x'},
                                       {'key': 'e_1_2_8_33_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.2307/2404467'},
                                       {'key': 'e_1_2_8_34_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1093/jxb/ert061'},
                                       {'key': 'e_1_2_8_35_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1657/1523-0430(2003)035[0361:TROPIA]2.0.CO;2'},
                                       {'key': 'e_1_2_8_36_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1002/joc.3444'},
                                       {'key': 'e_1_2_8_37_1',
                                        'article-title': 'Advances in flowering phenology across the '
                                                         'northern hemisphere are explained by functional '
                                                         'traits',
                                        'author': 'König P.',
                                        'year': '2018',
                                        'journal-title': 'Global Ecology and Biogeography'},
                                       {'key': 'e_1_2_8_38_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s00442-012-2581-8'},
                                       {'key': 'e_1_2_8_39_1',
                                        'volume-title': 'Ökophysiologie der Pflanzen',
                                        'author': 'Larcher W.',
                                        'year': '1994'},
                                       {'key': 'e_1_2_8_40_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/gcb.12360'},
                                       {'key': 'e_1_2_8_41_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1139/cjb-2014-0026'},
                                       {'key': 'e_1_2_8_42_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/gcb.13311'},
                                       {'key': 'e_1_2_8_43_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s10342-013-0775-1'},
                                       {'key': 'e_1_2_8_44_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s004840000054'},
                                       {'issue': '659',
                                        'key': 'e_1_2_8_45_1',
                                        'doi-asserted-by': 'crossref',
                                        'first-page': '659',
                                        'DOI': '10.1038/17709',
                                        'article-title': 'Growing season extended in Europe',
                                        'volume': '397',
                                        'author': 'Menzel A.',
                                        'year': '1999',
                                        'journal-title': 'Nature'},
                                       {'key': 'e_1_2_8_46_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1365-2486.2006.01193.x'},
                                       {'key': 'e_1_2_8_47_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s00484-008-0152-9'},
                                       {'key': 'e_1_2_8_48_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1016/j.agrformet.2011.05.012'},
                                       {'key': 'e_1_2_8_49_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1890/07-0068.1'},
                                       {'key': 'e_1_2_8_50_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1469-8137.2010.03252.x'},
                                       {'key': 'e_1_2_8_51_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1038/nature01286'},
                                       {'key': 'e_1_2_8_52_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s10342-012-0646-1'},
                                       {'key': 'e_1_2_8_53_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1071/BT12225'},
                                       {'key': 'e_1_2_8_54_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1469-8137.2009.02830.x'},
                                       {'key': 'e_1_2_8_55_1',
                                        'volume-title': 'R: A language and environment for statistical '
                                                        'computing',
                                        'author': 'R Core Team',
                                        'year': '2016'},
                                       {'key': 'e_1_2_8_56_1',
                                        'unstructured': 'de Réaumur R. A. F.(1735).Observation du '
                                                        "thermometer faites à Paris pendant l'année 1735 "
                                                        'compares avec celles qui ont été faites sous la '
                                                        "ligne à l'Isle de France à Alger et en "
                                                        "quelques‐unes de nos isles de l'Amérique. Mémoires "
                                                        "de l'Académie des Sciences de Paris (1735)."},
                                       {'key': 'e_1_2_8_57_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1073/pnas.94.25.13730'},
                                       {'key': 'e_1_2_8_58_1',
                                        'unstructured': 'Ridgeway(2015).gbm: Generalized Boosted Regression '
                                                        'Models. R package version 2.1.1. Retrieved '
                                                        'fromhttps://CRAN.R-project.org/package=gbm'},
                                       {'key': 'e_1_2_8_59_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1469-8137.2005.01460.x'},
                                       {'key': 'e_1_2_8_60_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s12224-016-9250-3'},
                                       {'key': 'e_1_2_8_61_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1046/j.1365-2435.1999.00010.x'},
                                       {'key': 'e_1_2_8_62_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1046/j.0016-8025.2003.01058.x'},
                                       {'key': 'e_1_2_8_63_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/plb.12071'},
                                       {'key': 'e_1_2_8_64_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s00484-013-0709-0'},
                                       {'key': 'e_1_2_8_65_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s004840000049'},
                                       {'key': 'e_1_2_8_66_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1111/j.1365-2745.2011.01830.x'},
                                       {'key': 'e_1_2_8_67_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1016/j.agrformet.2008.10.019'},
                                       {'key': 'e_1_2_8_68_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1007/s00442-009-1363-4'},
                                       {'issue': '2',
                                        'key': 'e_1_2_8_69_1',
                                        'doi-asserted-by': 'crossref',
                                        'first-page': '349',
                                        'DOI': '10.1007/s00484-016-1216-x',
                                        'article-title': "‘Hearing'alpine plants growing after snowmelt: "
                                                         'Ultrasonic snow sensors provide long‐term series '
                                                         'of alpine plant phenology',
                                        'volume': '61',
                                        'author': 'Vitasse Y.',
                                        'year': '2016',
                                        'journal-title': 'International Journal of Biometeorology'},
                                       {'key': 'e_1_2_8_70_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1890/08-0127.1'},
                                       {'key': 'e_1_2_8_71_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1890/ES15-00070.1'},
                                       {'key': 'e_1_2_8_72_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1073/pnas.0806446105'},
                                       {'key': 'e_1_2_8_73_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1038/nature11014'},
                                       {'key': 'e_1_2_8_74_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.1002/jpln.201500539'},
                                       {'key': 'e_1_2_8_75_1',
                                        'doi-asserted-by': 'publisher',
                                        'DOI': '10.3354/cr00822'}],
                         'container-title': ['Ecology and Evolution'],
                         'original-title': [],
                         'language': 'en',
                         'link': [{'URL': 'https://api.wiley.com/onlinelibrary/tdm/v1/articles/10.1002%2Fece3.3720',
                                   'content-type': 'application/pdf',
                                   'content-version': 'vor',
                                   'intended-application': 'text-mining'},
                                  {'URL': 'https://onlinelibrary.wiley.com/doi/pdf/10.1002/ece3.3720',
                                   'content-type': 'unspecified',
                                   'content-version': 'vor',
                                   'intended-application': 'similarity-checking'}],
                         'deposited': {'date-parts': [[2023, 9, 17]],
                                       'date-time': '2023-09-17T12:21:04Z',
                                       'timestamp': 1694953264000},
                         'score': 1,
                         'resource': {'primary': {'URL': 'https://onlinelibrary.wiley.com/doi/10.1002/ece3.3720'}},
                         'subtitle': [],
                         'short-title': [],
                         'issued': {'date-parts': [[2017, 12, 20]]},
                         'references-count': 74,
                         'journal-issue': {'issue': '2', 'published-print': {'date-parts': [[2018, 1]]}},
                         'alternative-id': ['10.1002/ece3.3720'],
                         'URL': 'https://doi.org/10.1002/ece3.3720',
                         'archive': ['Portico'],
                         'relation': {},
                         'ISSN': ['2045-7758', '2045-7758'],
                         'issn-type': [{'value': '2045-7758', 'type': 'print'},
                                       {'value': '2045-7758', 'type': 'electronic'}],
                         'subject': [],
                         'published': {'date-parts': [[2017, 12, 20]]}}}}
